### PR TITLE
Fix 2.7 compatibility issues

### LINKED ISSUE #14: python2.7 depends on `future` library
`pfs_client.py` imports `builtins`, which is not present in a minimal python2.7 installation. This can be fixed by installing the `future` library via pip.

example:

```
root@0fb4804911b6:/opt# python
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypachy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pypachy/__init__.py", line 1, in <module>
    from .pfs_client import PfsClient, DIR, FILE, NONE, JSON, LINE
  File "/usr/local/lib/python2.7/dist-packages/pypachy/pfs_client.py", line 3, in <module>
    from builtins import object
ImportError: No module named builtins
```

and to fix:

```
root@0fb4804911b6:/opt# pip install future
Collecting future
  Downloading future-0.16.0.tar.gz (824kB)
    100% |################################| 829kB 1.4MB/s
Building wheels for collected packages: future
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
Successfully built future
Installing collected packages: future
Successfully installed future-0.16.0
root@0fb4804911b6:/opt# python
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pypachy
>>> exit
```

### PR DESCRIPTION
**Pull request by dargueta**
* Hopefully closes #14 and #28
* Start testing on all versions this library states it supports

### CODE REVIEW

**Comment by ysimonson** [comment]
@dargueta Thanks for this, and apologies for the delay. I've made a bunch of fixes - could you merge the latest from master? That should hopefully get tests passing.

**Comment by ysimonson** [comment]
It looks like each worker is trying to build all of the python variants. I think the way to fix is to:

* Set `TOXENV` in each of the TravisCI worker variations, see [here for an example](https://github.com/indradb/python-client/blob/master/.travis.yml).
* Set `basepython` in each of the variants in tox.ini.

**Comment by dargueta** [comment]
@ysimonson looks like the compatibility problems have been solved.

**Comment by ysimonson** [comment]
Thanks for this!

**Pull request merged**
