### PR TITLE
Add overwrite_index option to put_file_url

### PR DESCRIPTION
**Pull request by OliverEvans96**
I noticed that the put_file_url function had no overwrite_index option.

@JoeyZwicker asked me to open an issue, but it was simple enough I thought I'd just add the option myself.

Let me know if there's anything else I can do here.

Thanks!
Oliver

### CODE REVIEW

**Comment by ysimonson** [comment]
Thanks!

**Comment by OliverEvans96** [comment]
@ysimonson does this package have a regular release schedule? When can I expect this change to make it into PyPI?

**Comment by ysimonson** [comment]
There's no specific release schedule, but I went ahead and pushed it out just now - 1.9.0.post6

**Comment by OliverEvans96** [comment]
Awesome, thanks!!

**Pull request merged**
